using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CosmoApiServer.SourceGenerator;

[Generator]
internal class RazorSliceProxyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyName = context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName);

        var rootNamespace = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace) ? rootNamespace : null);

        var projectDirectory = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var projectDir) ? projectDir : null);

        var projectInfo = assemblyName.Combine(rootNamespace.Combine(projectDirectory));

        var allRazorFiles = context.AdditionalTextsProvider
            .Where(text => text.Path.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase) || 
                           text.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase));

        // Simplified: Slices are any .cshtml/.razor that are NOT _ViewImports.cshtml or _Imports.razor
        var sliceTexts = allRazorFiles
            .Where(file => !Path.GetFileName(file.Path).Equals("_ViewImports.cshtml", StringComparison.OrdinalIgnoreCase) &&
                           !Path.GetFileName(file.Path).Equals("_Imports.razor", StringComparison.OrdinalIgnoreCase));

        var combined = projectInfo
            .Combine(sliceTexts.Collect())
            .Combine(allRazorFiles.Collect())
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var compilation = pair.Right;
            var allFiles = pair.Left.Right;
            var slices = pair.Left.Left.Right;
            var info = pair.Left.Left.Left;

            Execute(spc,
                info.Left,
                info.Right.Left,
                info.Right.Right,
                slices,
                allFiles,
                compilation);
        });
    }

    private static void Execute(
        SourceProductionContext context,
        string? assemblyName,
        string? rootNamespace,
        string? projectDirectory,
        ImmutableArray<AdditionalText> sliceTexts,
        ImmutableArray<AdditionalText> allRazorFiles,
        Compilation compilation)
    {
        if (string.IsNullOrEmpty(rootNamespace) || string.IsNullOrEmpty(projectDirectory)) return;

        var distinctTexts = sliceTexts.Distinct();
        if (!distinctTexts.Any()) return;

        var viewImportsMap = ViewImportsResolver.BuildViewImportsMap(allRazorFiles);
        HashSet<string> generatedClasses = [];
        var codeBuilder = new StringBuilder();

        codeBuilder.AppendLine("// <auto-generated/>");
        codeBuilder.AppendLine();
        codeBuilder.AppendLine("using global::System.Diagnostics.CodeAnalysis;");
        codeBuilder.AppendLine("using global::CosmoApiServer.Core.Templates;");
        codeBuilder.AppendLine();
        codeBuilder.AppendLine("#nullable enable");
        codeBuilder.AppendLine();

        foreach (var file in distinctTexts)
        {
            var isRazor = file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase);
            var fileName = Path.GetFileNameWithoutExtension(file.Path);
            var directory = Path.GetDirectoryName(file.Path);
            var relativeFilePath = PathUtils.GetRelativePath(projectDirectory!, file.Path);
            var relativeDirectoryPath = PathUtils.GetRelativePath(projectDirectory!, directory);
            var subNamespace = relativeDirectoryPath == "." ? "" : relativeDirectoryPath.Replace(Path.DirectorySeparatorChar, '.');

            var className = CSharpHelpers.IsValidTypeName(fileName) ? fileName : CSharpHelpers.CreateValidTypeName(fileName);
            if (!string.IsNullOrEmpty(subNamespace) && !CSharpHelpers.IsValidNamespace(subNamespace))
                subNamespace = CSharpHelpers.CreateValidNamespace(subNamespace);

            var subNamespaceAsClassName = subNamespace.Replace('.', '_');
            var fullNamespace = string.IsNullOrEmpty(subNamespace) ? rootNamespace : $"{rootNamespace}.{subNamespace}";

            if (generatedClasses.Contains($"{fullNamespace}.{className}")) continue;
            generatedClasses.Add($"{fullNamespace}.{className}");

            var sourceText = file.GetText();
            string? resolvedModelType = null;
            bool hasModel = false;
            var templateNameSpace = isRazor ? fullNamespace : "AspNetCoreGeneratedDocument"; // .razor usually keeps namespace
            var routes = new List<string>();

            if (sourceText is not null)
            {
                if (isRazor)
                {
                    routes = RazorDirectiveParser.ParsePageDirectives(sourceText);
                }

                var directives = ViewImportsResolver.ResolveDirectives(file.Path, projectDirectory!, viewImportsMap, sourceText);
                if (directives.InheritsDirective is not null)
                {
                    var baseType = RazorDirectiveParser.ExtractBaseTypeName(directives.InheritsDirective);
                    if (IsCosmoSliceBaseType(baseType))
                    {
                        var modelType = RazorDirectiveParser.ExtractModelType(directives.InheritsDirective);
                        if (modelType is not null)
                        {
                            resolvedModelType = ModelTypeResolver.ResolveModelType(modelType, directives.UsingDirectives, compilation, rootNamespace);
                            if (resolvedModelType is not null) hasModel = true;
                        }
                    }
                    else
                    {
                        resolvedModelType = ModelTypeResolver.ResolveModelTypeFromSliceBaseType(directives.InheritsDirective, directives.UsingDirectives, compilation, rootNamespace);
                        if (resolvedModelType is not null) hasModel = true;
                    }
                }
                if (directives.NamespaceDirective is not null) templateNameSpace = directives.NamespaceDirective;
            }

            codeBuilder.AppendLine($$"""
                namespace {{fullNamespace}}
                {
                """);

            if (isRazor && routes.Any())
            {
                foreach (var route in routes)
                {
                    codeBuilder.AppendLine($$"""    [global::Microsoft.AspNetCore.Components.RouteAttribute("{{route}}")]""");
                }
            }

            codeBuilder.AppendLine($$"""
                    public sealed partial class {{className}}
                    {
                        private const string TypeName = "{{(isRazor ? $"{fullNamespace}.{className}" : $"{templateNameSpace}.{(string.IsNullOrEmpty(subNamespaceAsClassName) ? className : $"{subNamespaceAsClassName}_{className}")}")}}, {{assemblyName}}";
                        private static readonly global::System.Type _sliceType = global::System.Type.GetType(TypeName)!;
                """);

            // Emit @inject properties for components (.cshtml only, .razor SDK handles .razor)
            var injectDirectives = sourceText is not null
                ? ViewImportsResolver.ResolveDirectives(file.Path, projectDirectory!, viewImportsMap, sourceText).InjectDirectives
                : new List<InjectDirective>();

            if (!isRazor && injectDirectives.Count > 0)
            {
                foreach (var inject in injectDirectives)
                {
                    codeBuilder.AppendLine($$"""
                        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInject]
                        public {{inject.TypeName}} {{inject.PropertyName}} { get; set; } = default!;
                """);
                }
            }

            if (isRazor)
            {
                // For components, we don't usually have a single 'Model'. We have Parameters.
                // But for SSR, we might want a factory that sets some initial parameters.
                codeBuilder.AppendLine($$"""
                        public static global::CosmoApiServer.Core.Templates.ComponentBase Create(global::System.Action<{{className}}>? configure = null)
                        {
                            var component = ({{className}})global::System.Activator.CreateInstance(_sliceType)!;
                            configure?.Invoke(component);
                            return component;
                        }
                """);
            }
            else
            {
                if (hasModel && resolvedModelType is not null)
                {
                    codeBuilder.AppendLine($$"""
                            public static global::CosmoApiServer.Core.Templates.RazorSlice<{{resolvedModelType}}> Create({{resolvedModelType}} model)
                            {
                                var slice = (global::CosmoApiServer.Core.Templates.RazorSlice<{{resolvedModelType}}>)global::System.Activator.CreateInstance(_sliceType)!;
                                slice.Model = model;
                                return slice;
                            }
                    """);
                }
                else
                {
                    codeBuilder.AppendLine($$"""
                            public static global::CosmoApiServer.Core.Templates.RazorSlice Create()
                            {
                                return (global::CosmoApiServer.Core.Templates.RazorSlice)global::System.Activator.CreateInstance(_sliceType)!;
                            }
                    """);
                }
            }

            codeBuilder.AppendLine("""
                    }
                }
                """);
        }

        context.AddSource($"{rootNamespace}.CosmoSlices.g.cs", SourceText.From(codeBuilder.ToString(), Encoding.UTF8));
    }

    private static bool IsCosmoSliceBaseType(string baseTypeName) =>
        baseTypeName == "RazorSlice" || baseTypeName == "CosmoApiServer.Core.Templates.RazorSlice";
}
