using System.Text.Json;
using Microsoft.AspNetCore.Components.Rendering;

namespace Microsoft.AspNetCore.Components;

/// <summary>
/// Renders a lightweight SSR-friendly HTML editor backed by a hidden form field.
/// </summary>
public class HtmlEditor : ComponentBase
{
    private static readonly MarkupString Styles = new(HtmlEditorAssets.StyleBlock);

    /// <summary>
    /// Gets or sets the form field name that receives the editor HTML.
    /// </summary>
    [Parameter]
    public string FieldName { get; set; } = "htmlBody";

    /// <summary>
    /// Gets or sets the initial HTML value.
    /// </summary>
    [Parameter]
    public string Value { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets placeholder text shown when the editor is empty.
    /// </summary>
    [Parameter]
    public string Placeholder { get; set; } = "Write your message...";

    /// <summary>
    /// Gets or sets an optional id prefix. A stable value is generated by default.
    /// </summary>
    [Parameter]
    public string EditorId { get; set; } = $"html-editor-{Guid.NewGuid():N}";

    /// <summary>
    /// Gets or sets the minimum editor height in CSS units.
    /// </summary>
    [Parameter]
    public string MinHeight { get; set; } = "280px";

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        var hiddenInputId = $"{EditorId}-value";
        var editorElementId = $"{EditorId}-surface";
        var syncScript = HtmlEditorAssets.BuildSyncScript(EditorId);

        builder.AddContent(0, Styles);

        builder.OpenElement(1, "div");
        builder.AddAttribute(2, "class", "cosmo-html-editor");
        builder.AddAttribute(3, "data-editor-id", EditorId);

        builder.OpenElement(4, "input");
        builder.AddAttribute(5, "type", "hidden");
        builder.AddAttribute(6, "name", FieldName);
        builder.AddAttribute(7, "id", hiddenInputId);
        builder.AddAttribute(8, "value", Value ?? string.Empty);
        builder.CloseElement();

        builder.OpenElement(9, "div");
        builder.AddAttribute(10, "class", "cosmo-html-editor-toolbar");
        builder.AddAttribute(11, "role", "toolbar");
        builder.AddAttribute(12, "aria-label", "Formatting toolbar");
        AddTool(builder, 20, "B", HtmlEditorAssets.BuildCommandScript(EditorId, "bold"), "Bold", true);
        AddTool(builder, 30, "I", HtmlEditorAssets.BuildCommandScript(EditorId, "italic"), "Italic", false, "font-style:italic;");
        AddTool(builder, 40, "U", HtmlEditorAssets.BuildCommandScript(EditorId, "underline"), "Underline", false, "text-decoration:underline;");
        AddSeparator(builder, 50);
        AddTool(builder, 60, "• List", HtmlEditorAssets.BuildCommandScript(EditorId, "insertUnorderedList"), "Bullet list");
        AddTool(builder, 70, "1. List", HtmlEditorAssets.BuildCommandScript(EditorId, "insertOrderedList"), "Numbered list");
        AddSeparator(builder, 80);
        AddTool(builder, 90, "P", HtmlEditorAssets.BuildCommandScript(EditorId, "formatBlock", "<p>"), "Paragraph");
        AddTool(builder, 100, "H2", HtmlEditorAssets.BuildCommandScript(EditorId, "formatBlock", "<h2>"), "Heading");
        AddTool(builder, 110, "Link", HtmlEditorAssets.BuildLinkScript(EditorId), "Insert link");
        AddTool(builder, 120, "Clear", HtmlEditorAssets.BuildClearScript(EditorId), "Clear formatting");
        builder.CloseElement();

        builder.OpenElement(130, "div");
        builder.AddAttribute(131, "id", editorElementId);
        builder.AddAttribute(132, "class", "cosmo-html-editor-surface");
        builder.AddAttribute(133, "contenteditable", "true");
        builder.AddAttribute(134, "data-placeholder", Placeholder);
        builder.AddAttribute(135, "style", $"min-height:{MinHeight};");
        builder.AddAttribute(136, "oninput", syncScript);
        builder.AddContent(137, new MarkupString(Value ?? string.Empty));
        builder.CloseElement();

        builder.CloseElement();
    }

    private static void AddTool(RenderTreeBuilder builder, int seq, string label, string onclick, string title, bool strong = false, string? inlineStyle = null)
    {
        builder.OpenElement(seq, "button");
        builder.AddAttribute(seq + 1, "type", "button");
        builder.AddAttribute(seq + 2, "class", "cosmo-html-editor-tool");
        builder.AddAttribute(seq + 3, "title", title);
        builder.AddAttribute(seq + 4, "onclick", onclick);

        if (strong)
        {
            builder.OpenElement(seq + 5, "strong");
            builder.AddContent(seq + 6, label);
            builder.CloseElement();
        }
        else if (!string.IsNullOrWhiteSpace(inlineStyle))
        {
            builder.OpenElement(seq + 5, "span");
            builder.AddAttribute(seq + 6, "style", inlineStyle);
            builder.AddContent(seq + 7, label);
            builder.CloseElement();
        }
        else
        {
            builder.AddContent(seq + 5, label);
        }

        builder.CloseElement();
    }

    private static void AddSeparator(RenderTreeBuilder builder, int seq)
    {
        builder.OpenElement(seq, "span");
        builder.AddAttribute(seq + 1, "class", "cosmo-html-editor-sep");
        builder.CloseElement();
    }
}

internal static class HtmlEditorAssets
{
    public const string StyleBlock = """
<style>
.cosmo-html-editor{border:1px solid #d6d5d5;border-radius:12px;overflow:hidden;background:#fff;}
.cosmo-html-editor-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:6px;padding:10px;background:#f7f7f7;border-bottom:1px solid #e3e3e3;}
.cosmo-html-editor-tool{border:1px solid #d0d0d0;background:#fff;border-radius:8px;padding:7px 10px;cursor:pointer;font:inherit;}
.cosmo-html-editor-tool:hover{background:#f0f4ff;}
.cosmo-html-editor-sep{width:1px;height:24px;background:#d7d7d7;margin:0 2px;}
.cosmo-html-editor-surface{padding:16px;outline:none;background:#fff;}
.cosmo-html-editor-surface:empty:before{content:attr(data-placeholder);color:#888;}
</style>
""";

    public static string BuildSyncScript(string editorId)
    {
        return BuildScript($"const s=document.getElementById({Js(editorId + "-surface")});const i=document.getElementById({Js(editorId + "-value")});if(!s||!i) return; const h=s.innerHTML.trim(); i.value=(h==='<'+'br>'||h==='<div><br></div>')?'':h;");
    }

    public static string BuildCommandScript(string editorId, string command, string? value = null)
    {
        var valueArg = value is null ? "null" : Js(value);
        return BuildScript($"const s=document.getElementById({Js(editorId + "-surface")});if(!s) return; s.focus(); document.execCommand({Js(command)}, false, {valueArg}); const i=document.getElementById({Js(editorId + "-value")}); if(i){{const h=s.innerHTML.trim(); i.value=(h==='<'+'br>'||h==='<div><br></div>')?'':h;}}");
    }

    public static string BuildLinkScript(string editorId)
    {
        return BuildScript($"const url=window.prompt('Enter URL'); if(!url) return; const s=document.getElementById({Js(editorId + "-surface")}); if(!s) return; s.focus(); document.execCommand('createLink', false, url); const i=document.getElementById({Js(editorId + "-value")}); if(i){{const h=s.innerHTML.trim(); i.value=(h==='<'+'br>'||h==='<div><br></div>')?'':h;}}");
    }

    public static string BuildClearScript(string editorId)
    {
        return BuildScript($"const s=document.getElementById({Js(editorId + "-surface")});const i=document.getElementById({Js(editorId + "-value")});if(!s||!i) return; s.innerHTML=''; i.value=''; s.focus();");
    }

    private static string BuildScript(string body) => $"(function(){{{body}}})();";

    private static string Js(string value) => JsonSerializer.Serialize(value);
}
