using System.Text;
using CosmoApiServer.Core.Http;

namespace CosmoApiServer.Core.Templates;

/// <summary>
/// Base class for all Razor Slices in CosmoApiServer.
/// Analogous to RazorSlice in the original library.
/// </summary>
public abstract class RazorSlice
{
    private StringBuilder? _buffer;

    /// <summary>
    /// Gets or sets the HTTP context for the current request.
    /// </summary>
    public HttpContext HttpContext { get; internal set; } = null!;

    /// <summary>
    /// Executes the Razor template and writes it to the provided StringBuilder.
    /// This is the method generated by the Razor SDK.
    /// </summary>
    public abstract Task ExecuteAsync();

    /// <summary>
    /// Renders the slice to a string.
    /// </summary>
    public async Task<string> RenderAsync()
    {
        _buffer = new StringBuilder();
        await ExecuteAsync();
        return _buffer.ToString();
    }

    /// <summary>
    /// Renders the slice directly to the CosmoApiServer HttpResponse.
    /// </summary>
    public async Task RenderToResponseAsync(HttpResponse response)
    {
        // For now, we render to a string and then write to response.
        // In a more advanced version, we can override Write to write directly to response buffers.
        var html = await RenderAsync();
        response.WriteText(html, "text/html; charset=utf-8");
    }

    // ── Razor-required methods ─────────────────────────────────────────────

    protected void WriteLiteral(string? value) => _buffer?.Append(value);

    protected void Write(object? value)
    {
        if (value is HtmlString html)
            _buffer?.Append(html.ToString());
        else
            _buffer?.Append(HtmlEncoder.Encode(value));
    }

    protected void Write(string? value) => _buffer?.Append(HtmlEncoder.Encode(value));

    // ── Attribute and Tag Helper support (stubs) ───────────────────────────

    protected void BeginWriteAttribute(string name, string prefix, int prefixOffset, string suffix, int suffixOffset, int attributeValuesCount)
    {
        _buffer?.Append(prefix);
    }

    protected void WriteAttributeValue(string prefix, int prefixOffset, object? value, int valueOffset, int valueLength, bool isLiteral)
    {
        _buffer?.Append(prefix);
        if (isLiteral) _buffer?.Append(value);
        else Write(value);
    }

    protected void EndWriteAttribute()
    {
    }

    protected void StartTagHelperWritingScope(TextWriter writer) { }
    protected TextWriter EndTagHelperWritingScope() => null!;
    protected T CreateTagHelper<T>() where T : class, new() => new T();
}

/// <summary>
/// Base class for Razor Slices with a strongly-typed model.
/// </summary>
/// <typeparam name="TModel">The type of the model.</typeparam>
public abstract class RazorSlice<TModel> : RazorSlice
{
    public TModel Model { get; set; } = default!;
}
