using System.Text;
using System.Buffers;
using CosmoApiServer.Core.Http;

namespace CosmoApiServer.Core.Templates;

/// <summary>
/// Base class for all Razor Slices in CosmoApiServer.
/// Analogous to RazorSlice in the original library.
/// </summary>
public abstract class RazorSlice
{
    internal IBufferWriter<byte>? _bufferWriter;

    /// <summary>
    /// Gets or sets the HTTP context for the current request.
    /// </summary>
    public HttpContext HttpContext { get; internal set; } = null!;

    /// <summary>
    /// Executes the Razor template. 
    /// This is the method generated by the Razor SDK.
    /// </summary>
    public abstract Task ExecuteAsync();

    /// <summary>
    /// Renders the slice to a string.
    /// </summary>
    public async ValueTask<string> RenderAsync()
    {
        var adapter = new HttpResponse.TestBufferWriter();
        _bufferWriter = adapter;
        await ExecuteAsync();
        _bufferWriter = null;
        return Encoding.UTF8.GetString(adapter.ToArray());
    }

    /// <summary>
    /// Renders the slice directly to the CosmoApiServer HttpResponse.
    /// </summary>
    public async ValueTask RenderToResponseAsync(HttpResponse response)
    {
        response.Headers["Content-Type"] = "text/html; charset=utf-8";
        
        if (response.BodyWriter != null)
        {
            _bufferWriter = response.BodyWriter;
            await ExecuteAsync();
            _bufferWriter = null;
        }
        else
        {
            var html = await RenderAsync();
            response.WriteText(html, "text/html; charset=utf-8");
        }
    }

    // ── Razor-required methods ─────────────────────────────────────────────

    protected void WriteLiteral(string? value)
    {
        if (value == null || _bufferWriter == null) return;
        _bufferWriter.Write(Utf8LiteralCache.GetEncoded(value));
    }

    protected async ValueTask Write(object? value)
    {
        if (value == null || _bufferWriter == null) return;

        if (value is HtmlString html)
        {
            _bufferWriter.Write(Utf8LiteralCache.GetEncoded(html.ToString()));
        }
        else if (value is RenderToBufferDelegate fragment)
        {
            await fragment(_bufferWriter);
        }
        else
        {
            await HtmlEncoder.EncodeToWriterAsync(value, _bufferWriter);
        }
    }

    protected async ValueTask Write(string? value)
    {
        if (value == null || _bufferWriter == null) return;
        HtmlEncoder.EncodeToWriter(value, _bufferWriter);
    }


    // ── Attribute and Tag Helper support (stubs) ───────────────────────────

    protected void BeginWriteAttribute(string name, string prefix, int prefixOffset, string suffix, int suffixOffset, int attributeValuesCount)
    {
        WriteLiteral(prefix);
    }

    protected void WriteAttributeValue(string prefix, int prefixOffset, object? value, int valueOffset, int valueLength, bool isLiteral)
    {
        WriteLiteral(prefix);
        if (isLiteral) WriteLiteral(value?.ToString());
        else Write(value);
    }

    protected void EndWriteAttribute()
    {
    }

    protected void StartTagHelperWritingScope(TextWriter writer) { }
    protected TextWriter EndTagHelperWritingScope() => null!;
    protected T CreateTagHelper<T>() where T : class, new() => new T();
}

/// <summary>
/// Base class for Razor Slices with a strongly-typed model.
/// </summary>
/// <typeparam name="TModel">The type of the model.</typeparam>
public abstract class RazorSlice<TModel> : RazorSlice
{
    public TModel Model { get; set; } = default!;
}
